### ISSUE TITLE
Create an Gnatt Chart of Project Progress

### ISSUE THREAD

**Issue by pthom4** [sudo-eddy/sudo-eddy.github.io#25]
Construct a Gantt chart to indicate all the tasks that will be performed, and the estimates for each task.

**Comment by pthom4** [comment]
First Draft of GANTT chart
[Web Store Project.mpp.zip](https://github.com/sudo-eddy/ecommerce-group-fall-21/files/7654988/Web.Store.Project.mpp.zip)

**Comment by sudo-eddy** [comment]
can you post a screenshot of this? I am unable to open the file format. I'm on linux

**Comment by pthom4** [comment]
![Project_plan_Gantt_1](https://user-images.githubusercontent.com/91397107/144781564-74924f7e-e39d-417a-bbf2-112d66156e47.png)
![Project_plan_Gantt_2](https://user-images.githubusercontent.com/91397107/144781580-d20a1a10-47ea-4c0d-9fc1-7f21dbdba1b2.png)

**Comment by sudo-eddy** [comment]
#### This looks amazing! Few things I would consider doing.

- include the bugs, and reduce the progress percentage on those features affected by the bugs
Not every project is perfect, so we have to show the actual struggle. 
- Same with the timelines, give them more realistic completion dates, even make some spill into the following week.
- We won't have much time to integrate a testing framework into our project. What we can do is create a testing proposal. I can help with that, as well as a UAT document. Which is a end user acceptance testing procedure. We could juice it up and add a proposal for CI/CD. Don't worry if you don't know what I'm talking about it will look nice when it's all put together. I need at least 2 days. 
- Rename the project from Webstore project to `DevSwag`
- Use one more color on top of the blue for readability 
Other than that, this looks great. What else do we need?
Attached is the org chart I created. Really simple, at this point we just need to have the content to turn in. file:///home/eddy/Desktop/Screenshot%20from%202021-12-03%2019-40-54.png

**Comment by sudo-eddy** [comment]
Do we know if Prof. West is going to be able to access the document addressed in this issue? Is there a way to export it to `.pdf`?

**Comment by pthom4** [comment]
This PM utility is online and I think I have the ability to share the access with you, that way you can also make changes to the Project Plan. I will need your email to invite you to collaborate - let me know which email to use.

**Comment by sudo-eddy** [comment]
is this :point_up: the final version?

**Comment by sudo-eddy** [comment]
https://us05web.zoom.us/j/81104837449?pwd=RlJPSHVQcEZiM2tVWWNRbnQzd0dVQT09
